name: nugroho_javacode
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  
  app_settings: ^6.1.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.0

  change_app_package_name: ^1.5.0

  # Signature
  fast_rsa: ^3.8.0

  # Logger
  sentry_flutter: ^8.14.0

  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0

  geocoding: ^3.0.0
  geolocator: ^13.0.2

  pinput: ^5.0.1
  connectivity_plus: ^6.1.3
  device_info_plus: ^11.3.3
  flutter_speed_dial: ^7.0.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  flutter_easyloading: ^3.0.5
  panara_dialogs: ^0.1.5
  dio: ^5.8.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  safe_device: ^1.2.0
  freerasp: ^6.12.0
  permission_handler: ^11.4.0
  # flutter_windowmanager: ^0.2.0 
  flutter_localization: ^0.3.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_compass: ^0.8.1
  syncfusion_flutter_pdfviewer: ^28.2.12
  just_audio: ^0.9.46
  video_player: ^2.9.3
  chewie: ^1.11.0
  flutter_inappwebview: ^6.1.5
  flutter_cache_manager: ^3.4.1
  camera: ^0.11.1
  image: ^4.5.4
  google_mlkit_barcode_scanning: ^0.14.1
  qr_flutter: ^4.1.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  flutter_conditional_rendering: ^2.1.0
  pull_to_refresh: ^2.0.0
  iconsax: ^0.0.8
  local_auth: ^2.3.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  infinite_scroll_pagination: ^5.0.0
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  badges: ^3.1.2
  qiscus_chat_sdk: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/audios/
    - assets/videos/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Java-Code.png"