// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx33NA9GBROLwT6i0kumxDGyD2OLl3AVQ',
    appId: '1:1033602776342:web:3321ff3bbb3d466e9aa437',
    messagingSenderId: '1033602776342',
    projectId: 'java-code-50d3d',
    authDomain: 'java-code-50d3d.firebaseapp.com',
    storageBucket: 'java-code-50d3d.firebasestorage.app',
    measurementId: 'G-W9273ZTRSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1jgdjbtt3sF5-r3PHzCM0U8KXyIEbYE',
    appId: '1:1033602776342:android:1776a15b753a03ce9aa437',
    messagingSenderId: '1033602776342',
    projectId: 'java-code-50d3d',
    storageBucket: 'java-code-50d3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzbtlPA0OvzTCexlGV0xOASRTgqVvcn5Y',
    appId: '1:1033602776342:ios:943142eedac19c249aa437',
    messagingSenderId: '1033602776342',
    projectId: 'java-code-50d3d',
    storageBucket: 'java-code-50d3d.firebasestorage.app',
    iosClientId: '1033602776342-9b4723i12bq6d4jnmqjmc1lpap8jo65a.apps.googleusercontent.com',
    iosBundleId: 'com.venturo.javacode',
  );

}